import { vi } from 'vitest';

// 通用 Element Plus 组件 mock
export const elementPlusStubs = {
  'el-input': { template: '<div class="el-input"><slot /></div>', props: ['modelValue', 'placeholder'] },
  'el-input-number': { template: '<div class="el-input-number"><slot /></div>', props: ['modelValue'] },
  'el-select': { template: '<div class="el-select"><slot /></div>', props: ['modelValue'] },
  'el-option': { template: '<div class="el-option"><slot /></div>', props: ['value', 'label'] },
  'el-table': { template: '<div class="el-table"><slot /></div>', props: ['data'] },
  'el-table-column': { template: '<div class="el-table-column"><slot /></div>', props: ['label', 'prop'] },
  'el-button': { template: '<button class="el-button"><slot /></button>', props: ['type', 'size'] },
  'el-tag': { template: '<span class="el-tag"><slot /></span>', props: ['type'] },
  'el-pagination': { template: '<div class="el-pagination" />', props: ['total', 'pageSize'] },
  'el-dialog': { template: '<div class="el-dialog"><slot /></div>', props: ['modelValue', 'title'] },
  'el-form': { template: '<form class="el-form"><slot /></form>', props: ['model'] },
  'el-form-item': { template: '<div class="el-form-item"><slot /></div>', props: ['label'] },
  'el-switch': { template: '<div class="el-switch" />', props: ['modelValue'] },
  'el-popconfirm': { template: '<div class="el-popconfirm"><slot /></div>', props: ['title'] },
  'el-dropdown': { template: '<div class="el-dropdown"><slot /></div>' },
  'el-dropdown-menu': { template: '<div class="el-dropdown-menu"><slot /></div>' },
  'el-dropdown-item': { template: '<div class="el-dropdown-item"><slot /></div>' },
  'el-avatar': { template: '<div class="el-avatar"><slot /></div>', props: ['src', 'size'] },
  'el-empty': { template: '<div class="el-empty" />' },
  'el-card': { template: '<div class="el-card"><slot /></div>', props: ['shadow'] },
  'el-divider': { template: '<div class="el-divider"><slot /></div>' },
  'el-breadcrumb': { template: '<div class="el-breadcrumb"><slot /></div>' },
  'el-breadcrumb-item': { template: '<div class="el-breadcrumb-item"><slot /></div>' },
  'el-tooltip': { template: '<div class="el-tooltip"><slot /></div>' },
  'el-popover': { template: '<div class="el-popover"><slot /></div>' },
  'el-checkbox': { template: '<div class="el-checkbox"><slot /></div>' },
  'el-checkbox-group': { template: '<div class="el-checkbox-group"><slot /></div>' },
  'el-radio': { template: '<div class="el-radio"><slot /></div>' },
  'el-radio-group': { template: '<div class="el-radio-group"><slot /></div>' },
  'el-date-picker': { template: '<div class="el-date-picker" />', props: ['modelValue'] },
  'el-upload': { template: '<div class="el-upload"><slot /></div>' },
  'el-progress': { template: '<div class="el-progress" />', props: ['percentage'] },
  'el-badge': { template: '<div class="el-badge"><slot /></div>', props: ['value'] },
  'el-collapse': { template: '<div class="el-collapse"><slot /></div>' },
  'el-collapse-item': { template: '<div class="el-collapse-item"><slot /></div>' },
  'el-tabs': { template: '<div class="el-tabs"><slot /></div>' },
  'el-tab-pane': { template: '<div class="el-tab-pane"><slot /></div>' },
  'el-descriptions': { template: '<div class="el-descriptions"><slot /></div>' },
  'el-descriptions-item': { template: '<div class="el-descriptions-item"><slot /></div>' },
  'el-statistic': { template: '<div class="el-statistic"><slot /></div>' },
  'el-timeline': { template: '<div class="el-timeline"><slot /></div>' },
  'el-timeline-item': { template: '<div class="el-timeline-item"><slot /></div>' },
  'el-alert': { template: '<div class="el-alert"><slot /></div>' },
  'el-image': { template: '<div class="el-image" />', props: ['src'] },
  'el-link': { template: '<a class="el-link"><slot /></a>' },
  'el-result': { template: '<div class="el-result"><slot /></div>' },
  'el-backtop': { template: '<div class="el-backtop" />' },
  'el-config-provider': { template: '<div class="el-config-provider"><slot /></div>' },
};

// 通用 lucide 图标 stub
export const lucideIconsStub = {
  'Search': { template: '<div class="icon" />' },
  'Refresh': { template: '<div class="icon" />' },
  'Download': { template: '<div class="icon" />' },
  'Upload': { template: '<div class="icon" />' },
  'Edit': { template: '<div class="icon" />' },
  'Edit2': { template: '<div class="icon" />' },
  'Edit3': { template: '<div class="icon" />' },
  'Delete': { template: '<div class="icon" />' },
  'Plus': { template: '<div class="icon" />' },
  'Minus': { template: '<div class="icon" />' },
  'Check': { template: '<div class="icon" />' },
  'X': { template: '<div class="icon" />' },
  'Close': { template: '<div class="icon" />' },
  'MoreVertical': { template: '<div class="icon" />' },
  'MoreHorizontal': { template: '<div class="icon" />' },
  'Filter': { template: '<div class="icon" />' },
  'SortAsc': { template: '<div class="icon" />' },
  'SortDesc': { template: '<div class="icon" />' },
  'ChevronLeft': { template: '<div class="icon" />' },
  'ChevronRight': { template: '<div class="icon" />' },
  'ChevronDown': { template: '<div class="icon" />' },
  'ChevronUp': { template: '<div class="icon" />' },
  'ArrowLeft': { template: '<div class="icon" />' },
  'ArrowRight': { template: '<div class="icon" />' },
  'Home': { template: '<div class="icon" />' },
  'User': { template: '<div class="icon" />' },
  'Users': { template: '<div class="icon" />' },
  'Package': { template: '<div class="icon" />' },
  'Box': { template: '<div class="icon" />' },
  'ShoppingBag': { template: '<div class="icon" />' },
  'ClipboardList': { template: '<div class="icon" />' },
  'Heart': { template: '<div class="icon" />' },
  'MessageSquare': { template: '<div class="icon" />' },
  'Bell': { template: '<div class="icon" />' },
  'Shield': { template: '<div class="icon" />' },
  'Settings': { template: '<div class="icon" />' },
  'LogOut': { template: '<div class="icon" />' },
  'Menu': { template: '<div class="icon" />' },
  'Grid': { template: '<div class="icon" />' },
  'Eye': { template: '<div class="icon" />' },
  'EyeOff': { template: '<div class="icon" />' },
  'Lock': { template: '<div class="icon" />' },
  'Unlock': { template: '<div class="icon" />' },
  'Mail': { template: '<div class="icon" />' },
  'Phone': { template: '<div class="icon" />' },
  'MapPin': { template: '<div class="icon" />' },
  'Clock': { template: '<div class="icon" />' },
  'Calendar': { template: '<div class="icon" />' },
  'Star': { template: '<div class="icon" />' },
  'AlertTriangle': { template: '<div class="icon" />' },
  'AlertCircle': { template: '<div class="icon" />' },
  'CheckCircle': { template: '<div class="icon" />' },
  'XCircle': { template: '<div class="icon" />' },
  'Info': { template: '<div class="icon" />' },
  'TrendingUp': { template: '<div class="icon" />' },
  'BarChart3': { template: '<div class="icon" />' },
  'PieChart': { template: '<div class="icon" />' },
  'LineChart': { template: '<div class="icon" />' },
  'FileText': { template: '<div class="icon" />' },
  'Image': { template: '<div class="icon" />' },
  'Camera': { template: '<div class="icon" />' },
  'Smile': { template: '<div class="icon" />' },
  'Circle': { template: '<div class="icon" />' },
  'LayoutDashboard': { template: '<div class="icon" />' },
  'Inbox': { template: '<div class="icon" />' },
  'Loader': { template: '<div class="icon" />' },
  'RefreshCw': { template: '<div class="icon" />' },
  'ExternalLink': { template: '<div class="icon" />' },
  'Copy': { template: '<div class="icon" />' },
  'Scissors': { template: '<div class="icon" />' },
  'Paperclip': { template: '<div class="icon" />' },
  'Send': { template: '<div class="icon" />' },
};

// 获取所有 mock
export const getAllStubs = () => ({
  ...elementPlusStubs,
  ...lucideIconsStub,
});

// 创建 router mock
export const routerMock = {
  push: vi.fn(),
  replace: vi.fn(),
  back: vi.fn(),
  forward: vi.fn(),
  currentRoute: { value: { path: '/', name: 'Home', params: {} } },
};

// 创建 route mock
export const routeMock = {
  path: '/',
  name: 'Home',
  params: {},
  query: {},
  meta: {},
};
